### ISSUE TITLE
KeyError: 0 when loading pretrained model with keras version 2.2.4

### ISSUE THREAD

**Issue by diego-fustes** [nsu-ai-team/noise_supression#4]
Hi folks,

thanks for this contribution. I'm trying to install it in my computer, but I got the following error when trying to load the pretrained model:
`
Traceback (most recent call last):
  File "enhance_audio.py", line 104, in <module>
    ae = AudioEnhancer()
  File "enhance_audio.py", line 15, in __init__
    self.model = keras.models.load_model(os.path.join(os.path.dirname(__file__), 'model/md_10000iters.h5'))
  File "/media/diego/disco/software/anaconda3/lib/python3.6/site-packages/keras/models.py", line 233, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/media/diego/disco/software/anaconda3/lib/python3.6/site-packages/keras/models.py", line 307, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/media/diego/disco/software/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/media/diego/disco/software/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/media/diego/disco/software/anaconda3/lib/python3.6/site-packages/keras/models.py", line 1204, in from_config
    if 'class_name' not in config[0] or config[0]['class_name'] == 'Merge':
KeyError: 0`

Could you provide a pretrained model which is compatible with this Keras version or at least could you specify the expected Keras version in the setup file?

**Comment by plbecker** [comment]
I had the same error until upgrading to Keras version 2.2.4 with conda and uninstalling the pip-installed Keras 1.2.0. You might want to check which Keras version you have by typing 
`import keras`
`print(keras.__version__)`
In addition, the pretrained model didn't download properly for me. I suggest you navigate to the model location within this repository and just download it manually to the model location of this library

**Comment by DinoTheDinosaur** [comment]
@Pr0duktiv, thank you for your help! I added the Keras version to the set of dependencies.
Also, the model now could be also downloaded manually from gdrive: https://drive.google.com/file/d/1PC4YtkJauNGRHiqD1mqs7SEmM1qrlI2z/view?usp=sharing
